### ISSUE TITLE
Should render es5 component (no babelified .default)

### ISSUE THREAD

**Issue by dijs** [MoOx/metalsmith-react#2]
Error: Cannot find module 'react/lib/ReactDOMServer'

Any ideas?

**Comment by cameronjroe** [comment]
Can you share more details?

**Comment by MoOx** [comment]
What version are you using?

**Comment by dijs** [comment]
Latest on npm. 

It looks like your package is missing react-dom.

Possibly an issue with node/npm/react version combination?

Is this package using the latest react lib?

**Comment by MoOx** [comment]
That's weird because the project now rely on react 0.14, where there is no 'react/lib/ReactDOMServer' anymore (this string doesn't exist in this project btw) in favor of react-dom => https://github.com/MoOx/metalsmith-react/blob/cd46cfe1ea8ff90e99977422139ac95b79c08/src/index.js#L6
Can you double check the version you use and provide a stacktrace please?

**Comment by dijs** [comment]
Sure

**Comment by cameronjroe** [comment]
Try running `npm cache clean` and reinstall the [latest](https://github.com/MoOx/metalsmith-react/releases/tag/2.0.0)

**Comment by dijs** [comment]
Here is a zip of the test project I am trying to make work...

There is no error when I run. But the build files are not static HTML, they are just markdown still...

Maybe I am not understanding something.

[Source.zip](https://github.com/MoOx/metalsmith-react/files/94680/Source.zip)

**Comment by dijs** [comment]
Sorry, there was no package json in there. The only dependencies are metalsmith and metalsmith-react

**Comment by MoOx** [comment]
1. do not use "src/*.md" but "*.md" for the pattern. 
- rename default.jsx to default.js
- use babel-node instead of node

That should help.

**Comment by dijs** [comment]
Got a bit farther, but now getting this react error:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
.../blog-test/index.js:18
    throw err;
          ^
Invariant Violation: Element type is invalid: expected a string (for built-in components) 
```

**Comment by MoOx** [comment]
Now you are "just" facing a "classic" React issue that you only should solve.

**Comment by dijs** [comment]
I found the issue.

When using es6 compiled or classic react es5 code, the ```default``` throws the error above.

I would just check if the required object is a react class, then if not, pull the default property. 

Here is the line I am talking about:
https://github.com/MoOx/metalsmith-react/blob/master/src/index.js#L30

**Comment by MoOx** [comment]
Oh, good catch. PR is welcome :)

**Comment by dijs** [comment]
Okay
